spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/mahawthadar_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

groq.api.key=${GROQ_API_KEY:}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=${GROQ_API_MODEL:openai/gpt-oss-120b}

file.upload-dir=uploads
ocr.service.url=http://localhost:8000/ocr/extract

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

ai.material-context.max-characters=12000

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true
